name: Auto Sync Fork

on:
  schedule:
    - cron: '0 * * * *' # Every hour (you can adjust this)
  workflow_dispatch: # Allow manual trigger as well

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: shuva-shree/WikiDocs
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.email "baisya14shuvashree@gmail.com"
          git config --global user.name "shuva_shree"

      - name: Pull upstream changes
        run: |
          git remote add upstream https://github.com/prithwishpramanik/WikiDocs.git
          git fetch upstream
          git merge upstream/main
          git push origin main

